export const registerFormControls = [
  {
    name: "userName",
    label: "User Name",
    placeholder: "Enter your username",
    componentType: "input",
    type: "text",
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const LoginFormControls = [
  {
    name: "email",
    label: "Email",
    placceholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placceholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const addProductFormElements = [
  {
    label: "Title",
    name: "title",
    componentType: "input",
    type: "text",
    placeholder: "Enter product title",
  },
  {
    label: "Description",
    name: "description",
    componentType: "textarea",
    placeholder: "Enter product description",
  },
  {
    label: "Category",
    name: "category",
    componentType: "select",
    options: [
      { id: "men", label: "Men" },
      { id: "women", label: "Women" },
      { id: "kids", label: "Kids" },
      { id: "accessories", label: "Accessories" },
      { id: "footwear", label: "Footwear" },
      { id: "electronics", label: "Electronics" },
    ],
  },
  {
    label: "Brand",
    name: "brand",
    componentType: "select",
    options: [
      { id: "nike", label: "Nike" },
      { id: "adidas", label: "Adidas" },
      { id: "puma", label: "Puma" },
      { id: "reebok", label: "Reebok" },
      { id: "under-armour", label: "Under Armour" },
      { id: "levi", label: "Levi's" },
      { id: "zara", label: "Zara" },
      { id: "h&m", label: "H&M" },
      { id: "U.S polo", label: "U.S polo" },
      { id: "peter England", label: "Peter England" },
      { id: "calvin-klein", label: "Calvin Klein" },
      { id: "tommy-hilfiger", label: "Tommy Hilfiger" },
      { id: "ralph-lauren", label: "Ralph Lauren" },
      { id: "gap", label: "Gap" },
      { id: "forever-21", label: "Forever 21" },
      {id:"samsung", label:"Samsung"},
      {id:"apple", label:"Apple"},
      {id:"oneplus", label:"OnePlus"},
      {id:"sony", label:"Sony"},
      {id:"noise", label:"Noise"},
      {id:"xiaomi", label:"Xiaomi"},
      {id:"asus", label:"Asus"},
      {id:"lenovo", label:"Lenovo"},
      { id: "other", label: "Other" },
    ],
  },
  {
    label: "Price",
    name: "price",
    componentType: "input",
    type: "number",
    placeholder: "Enter product price",
  },
  {
    label: "Sale price",
    name: "salePrice",
    componentType: "input",
    type: "number",
    placeholder: "Enter product sale price(optional)",
  },
  {
    label: "Total Stock",
    name: "totalStock",
    componentType: "input",
    type: "number",
    placeholder: "Enter total stock",
  },
];

export const shoppingViewHeaderMenuItems = [
  {
    id: "home",
    label: "Home",
    path: "/shop/home",
  },
  {
    id: "products",
    label: "Products",
    path: "/shop/listing",
  },
  {
    id: "men",
    label: "Men",
    path: "/shop/listing",
  },
  {
    id: "women",
    label: "Women",
    path: "/shop/listing",
  },
  {
    id: "kids",
    label: "Kids",
    path: "/shop/listing",
  },
  {
    id: "footwear",
    label: "Footwear",
    path: "/shop/listing",
  },
  {
    id: "electronics",
    label: "Electronics",
    path: "/shop/listing",
  },
  {
    id: "accessories",
    label: "Accessories",
    path: "/shop/listing",
  },
];

export const categoryOptionsMap = {
  men: "Men",
  women: "Women",
  kids: "Kids",
  accessories: "Accessories",
  footwear: "Footwear",
  electronics: "Electronics",
};

export const brandOptionsMap = {
  nike: "Nike",
  adidas: "Adidas",
  puma: "Puma",
  reebok: "Reebok",
  "under-armour": "Under Armour",
  levi: "Levi's",
  zara: "Zara",
  "h&m": "H&M",
  "U.S polo": "U.S polo",
  "peter England": "Peter England",
  "calvin-klein": "Calvin Klein",
  "tommy-hilfiger": "Tommy Hilfiger",
  "ralph-lauren": "Ralph Lauren",
  gap: "Gap",
  "forever-21": "Forever 21",
  "samsung": "Samsung",
  "apple": "Apple",
  "oneplus": "OnePlus",
  "sony": "Sony",
  "noise": "Noise", 
  "xiaomi": "Xiaomi",
  "asus": "Asus",
  "lenovo": "Lenovo",
  other: "Other",
};

export const filterOptions = {
  category: [
    { id: "men", label: "Men" },
    { id: "women", label: "Women" },
    { id: "kids", label: "Kids" },
    { id: "footwear", label: "Footwear" },
    { id: "accessories", label: "Accessories" },
    { id: "electronics", label: "Electronics" },
  ],
  brand: [
    { id: "nike", label: "Nike" },
    { id: "adidas", label: "Adidas" },
    { id: "puma", label: "Puma" },
    { id: "reebok", label: "Reebok" },
    { id: "under-armour", label: "Under Armour" },
    { id: "levi", label: "Levi's" },
    { id: "zara", label: "Zara" },
    { id: "h&m", label: "H&M" },
    { id: "U.S polo", label: "U.S polo" },
    { id: "peter England", label: "Peter England" },
    { id: "calvin-klein", label: "Calvin Klein" },
    { id: "tommy-hilfiger", label: "Tommy Hilfiger" },
    { id: "ralph-lauren", label: "Ralph Lauren" },
    { id: "gap", label: "Gap" },
    { id: "forever-21", label: "Forever 21" },
    {id:"samsung", label:"Samsung"},
    {id:"apple", label:"Apple"},
    {id:"oneplus", label:"OnePlus"},
    {id:"sony", label:"Sony"},
    {id:"noise", label:"Noise"},
    {id:"xiaomi", label:"Xiaomi"},
    {id:"asus", label:"Asus"},
    {id:"lenovo", label:"Lenovo"},
    { id: "other", label: "Other" },
  ],
};

export const sortOptions = [
  { id: "price-lowtohigh", label: "Price: Low to High" },
  { id: "price-hightolow", label: "Price: High to Low" },
  { id: "title-atoz", label: "Title:A to Z" },
  { id: "title-ztoa", label: "Title: Z to A" },
];

export const addressFormControls = [
  {
    label: "Address",
    name: "address",
    componentType: "input",
    type: "text",
    placeholder: "Enter your address",
  },
  {
    label: "City",
    name: "city",
    componentType: "input",
    type: "text",
    placeholder: "Enter your city",
  },
  {
    label: "State",
    name: "state",
    componentType: "input",
    type: "text",
    placeholder: "Enter your statee",
  },
  {
    label: "Pincode",
    name: "pincode",
    componentType: "input",
    type: "text",
    placeholder: "Enter your pincode",
  },
  {
    label: "Phone",
    name: "phone",
    componentType: "input",
    type: "text",
    placeholder: "Enter your phone number",
  },
  {
    label: "Notes",
    name: "notes",
    componentType: "textarea",
    placeholder: "Enter any additional notes",
  },
];
